-d C:\Users\User\Desktop\GOWIN\NCKUES_MMSoC_Class_HDMI_exp\impl\gwsynthesis\hdmi_colorbar.vg
-p GW2A-18C-PBGA256-8
-pn GW2A-LV18PG256C8/I7
-cst C:\Users\User\Desktop\GOWIN\NCKUES_MMSoC_Class_HDMI_exp\src\hdmi_colorbar.cst
-cfg C:\Users\User\Desktop\GOWIN\NCKUES_MMSoC_Class_HDMI_exp\impl\pnr\device.cfg
-sdc C:\Users\User\Desktop\GOWIN\NCKUES_MMSoC_Class_HDMI_exp\src\hdmi_colorbar.sdc
-bit
-tr
-ph
-timing
-cst_error
-correct_hold 1
-route_maxfan 23
